/**
 * Analytics event contract.
 *
 * Events are PostHog-compatible (`event`, `distinct_id`, `properties`, `timestamp`)
 * so the official posthog-js SDK can post straight into our ingestion endpoints and
 * anything the team extracts from PostHog can read the same rows.
 *
 * DO NOT rename fields here without updating every module (see /AGENTS.md).
 */

export type VisitorKind = "human" | "agent";

/** Standard funnel steps, in order. Used by funnels, the simulator and the optimizer. */
export const FUNNEL_STEPS = [
  "$pageview",
  "product_viewed",
  "product_added",
  "checkout_started",
  "order_completed",
] as const;
export type FunnelStep = (typeof FUNNEL_STEPS)[number];

/** Well-known event names. Anything else is allowed but these have meaning downstream. */
export const EVENTS = {
  pageview: "$pageview",
  pageleave: "$pageleave",
  autocapture: "$autocapture",
  rageclick: "$rageclick",
  productViewed: "product_viewed",
  productAdded: "product_added",
  cartViewed: "cart_viewed",
  checkoutStarted: "checkout_started",
  shippingRevealed: "shipping_cost_revealed",
  checkoutStepCompleted: "checkout_step_completed",
  checkoutAbandoned: "checkout_abandoned",
  orderCompleted: "order_completed",
  /** Every call an AI agent makes to the agent surface (REST, MCP). */
  agentRequest: "agent_request",
  /** An agent/merchant negotiation round. */
  agentNegotiation: "agent_negotiation",
  /** An agent gave up. `properties.reason` says why. */
  agentAbandoned: "agent_abandoned",
} as const;

export interface EventProperties {
  /** Who produced this event. Required on everything we write ourselves. */
  visitor_kind?: VisitorKind;
  /** Self-reported or detected agent name, e.g. "grok-shopper", "GPTBot". */
  agent_name?: string;
  /** Session id (PostHog: $session_id). */
  $session_id?: string;
  $current_url?: string;
  $pathname?: string;
  $referrer?: string;
  $user_agent?: string;
  $device_type?: "Desktop" | "Mobile" | "Tablet";
  /** Experiment attribution. Set whenever the visitor is in an experiment. */
  experiment_id?: string;
  variant?: string;
  /** Version of the live PageSpec the visitor saw. */
  spec_version?: number;
  /** True for traffic generated by the simulator. Never hide this in the UI. */
  synthetic?: boolean;
  /** Simulator persona, e.g. "bargain-hunter". */
  persona?: string;
  /** Commerce fields. Money is always integer minor units (pence). */
  product_id?: string;
  price?: number;
  quantity?: number;
  revenue?: number;
  /** Agent surface fields. */
  tool?: string;
  ok?: boolean;
  /** Fields the agent asked for that the store did not provide. */
  missing?: string[];
  reason?: string;
  [key: string]: unknown;
}

export interface AnalyticsEvent {
  /** Unique id (uuid). Generated at ingestion if missing. */
  uuid: string;
  event: string;
  distinct_id: string;
  /** ISO-8601. */
  timestamp: string;
  properties: EventProperties;
}

/** Input shape accepted by EventStore.append (uuid/timestamp optional). */
export type AnalyticsEventInput = Omit<AnalyticsEvent, "uuid" | "timestamp"> & {
  uuid?: string;
  timestamp?: string;
};
