"use client";

import { useState } from "react";
import { AnimatePresence, motion } from "motion/react";
import { Radio } from "lucide-react";
import type { FeedRow } from "@/lib/console/format";
import { timeAgo } from "@/lib/console/format";
import { useNow } from "@/lib/console/hooks";
import { Panel, PanelHeader } from "@/components/ui/panel";
import { Tag } from "@/components/ui/badge";
import { Kbd } from "@/components/ui/kbd";
import { cn } from "@/components/ui/cn";

const TONE: Record<FeedRow["tone"], string> = {
  default: "text-white/75",
  good: "text-[#8ff0b2]",
  bad: "text-[#ff9b9b]",
  warn: "text-[#ffd27a]",
  dim: "text-white/40",
};

function Row({ row, now }: { row: FeedRow; now: number }) {
  return (
    <motion.li
      initial={{ opacity: 0, height: 0, backgroundColor: "rgba(255,255,255,0.07)" }}
      animate={{ opacity: 1, height: "auto", backgroundColor: "rgba(255,255,255,0)" }}
      exit={{ opacity: 0, transition: { duration: 0.15 } }}
      transition={{ height: { type: "spring", stiffness: 500, damping: 40 }, opacity: { duration: 0.25 }, backgroundColor: { duration: 1.4 } }}
      className="overflow-hidden rounded-lg"
    >
      <div className="relative flex items-start gap-2.5 px-2 py-[0.4rem]">
      {(row.tone === "good" || row.tone === "bad") && (
        <span className={cn("absolute top-2 bottom-2 left-0 w-[2px] rounded-full", row.tone === "good" ? "bg-good" : "bg-bad")} />
      )}
      <span
        className={cn(
          "mt-[0.05rem] flex size-[1.55rem] shrink-0 items-center justify-center rounded-full text-[0.85rem]",
          row.kind === "agent" ? "bg-agent/15" : "bg-human/15",
        )}
      >
        {row.kind === "agent" ? "🤖" : "🧑"}
      </span>
      <div className="min-w-0 flex-1">
        <div className="truncate text-[0.84rem] leading-snug">
          <span className={cn("font-semibold", row.kind === "agent" ? "text-[#f5a6cb]" : "text-[#9cc5ff]")}>{row.actor}</span>{" "}
          <span className={TONE[row.tone]}>{row.text}</span>
        </div>
        <div className="mt-0.5 flex items-center gap-1.5 text-[0.68rem] text-white/30">
          {row.synthetic && <Tag title="Generated by the simulator (properties.synthetic)">Synthetic</Tag>}
          {row.variant && (
            <span
              className={cn(
                "rounded px-1 font-mono text-[0.6rem] font-bold",
                row.variant === "treatment" ? "bg-brand/20 text-brand" : "bg-control/20 text-white/60",
              )}
              title={`Experiment arm: ${row.variant}`}
            >
              {row.variant === "treatment" ? "B" : row.variant === "control" ? "A" : row.variant}
            </span>
          )}
          {row.detail && <span className="truncate">{row.detail}</span>}
          <span className="ml-auto shrink-0 tabular">{now ? timeAgo(row.at, now) : ""}</span>
        </div>
      </div>
      </div>
    </motion.li>
  );
}

export function LiveFeed({ rows, rate, trafficOn }: { rows: FeedRow[]; rate: number; trafficOn: boolean }) {
  const now = useNow();
  const [filter, setFilter] = useState<"all" | "human" | "agent">("all");
  const shown = filter === "all" ? rows : rows.filter((r) => r.kind === filter);
  return (
    <Panel className="h-full">
      <PanelHeader
        icon={<Radio />}
        title={
          <span className="flex items-center gap-2">
            Live traffic
            {trafficOn && <span className="size-1.5 rounded-full bg-good pulse-dot" />}
          </span>
        }
        right={
          <div className="flex items-center gap-2">
            {rate > 0 && <span className="font-mono text-[0.72rem] text-white/40 tabular">{Math.round(rate)} ev/s</span>}
            <div className="flex rounded-lg border border-white/[0.08] bg-white/[0.03] p-0.5 text-[0.72rem]">
              {(
                [
                  ["all", "All"],
                  ["human", "🧑"],
                  ["agent", "🤖"],
                ] as const
              ).map(([k, label]) => (
                <button
                  key={k}
                  onClick={() => setFilter(k)}
                  className={cn("rounded-md px-2 py-0.5 transition-colors", filter === k ? "bg-white/10 text-white" : "text-white/45 hover:text-white/80")}
                >
                  {label}
                </button>
              ))}
            </div>
          </div>
        }
      />
      {shown.length === 0 ? (
        <div className="flex flex-1 flex-col items-center justify-center gap-2 px-6 text-center text-[0.85rem] text-white/35">
          <Radio className="size-6 text-white/15" />
          {trafficOn ? "Waiting for shoppers…" : (
            <span>
              Quiet. Press <Kbd>T</Kbd> to send simulated humans and AI agents to the store.
            </span>
          )}
        </div>
      ) : (
        <ul className="fade-bottom min-h-0 flex-1 overflow-hidden px-3 pb-2">
          <AnimatePresence initial={false}>
            {shown.map((r) => (
              <Row key={r.id} row={r} now={now} />
            ))}
          </AnimatePresence>
        </ul>
      )}
    </Panel>
  );
}
